# Generated by Django 4.1.7 on 2023-04-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_category_section_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='section',
            new_name='category',
        ),
    ]
